on:
  pull_request:
    types:
      - opened
jobs:
  comment_for_pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Logging files
        run: ls -la

      - name: Commenting
        uses: hanlinthedev/JavaScript-Actions@1.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          giphy-api-key: ${{secrets.GIPHY_APIKEY}}
